/**
* BE AWARE THAT ALL VARIABLES STORED IN THIS FILE ARE ACCESSIBLE
* ON THE CLIENT SIDE AND ARE NOT SAFE.
*/
export default {
    'CONTENTFUL_SPACE_ID': '',
    'CONTENTFUL_CDA_ACCESS_TOKEN': '',
    'GTM_TRACKING_ID': ''
}